### ISSUE TITLE
Usage with luigi command line tool

### ISSUE THREAD

**Issue by ollikaven** [hudl/luigi-monitor#4]
Can I use luigi-monitor with luigi command line tool? I'm running my job with:

luigi --module example_module RangeDailyBase --of ExampleTaskName --start 2016-06-01 --days-back 4 --days-forward -1 --workers 2

I haven't been able to get the above working with luigi.run().

**Comment by alexdebrie** [comment]
Hey @ollikaven, the short answer is no, it doesn't work with the Luigi command line tool. However, if you make some minimal changes to your setup, you should be able to get the same behavior.

Steps:
1. First, add this to the bottom of every module with a luigi Task that you might call from the command line:
   
   ``` python
   if __name__ == "__main__":
       import luigi
       from luigi_monitor import monitor
       with monitor(slack_url=<your_slack_url>, max_print=10):
           luigi.run()
   ```
2. When running from the command line, change `luigi --module example_module` to `python <path/to/module>`. In your example, you wanted to call `ExampleTaskName` which is in your `example_module.py`. So your new command would be:
   
   ```
   python example_module.py RangeDailyBase --of ExampleTaskName --start 2016-06-01 --days-back 4 --days-forward -1 --workers 2
   ```

Let me know if you have any problems

**Comment by ollikaven** [comment]
That worked perfectly, thanks!
