### ISSUE TITLE
Incompatible with new luigi binary

### ISSUE THREAD

**Issue by dylanjbarth** [hudl/luigi-monitor#5]
In luigi 2, the recommended way to trigger a luigi task from the command line is using the `luigi` console script, with passes on run args to https://github.com/spotify/luigi/blob/master/luigi/cmdline.py#L11 

Two issues: 
- can't use a context manager with this invocation
- luigi now raises a SystemExit which would short circuit the context manager anyway. 

I'm thinking a nice way to solve this would be a console script in luigi-monitor that acts as a light wrapper around the luigi entry point. Any interest in this? Or other ideas?

**Comment by alexdebrie** [comment]
Hey @dylanjbarth, another user brought up a similar point in [this issue](https://github.com/hudl/luigi-monitor/issues/4). I gave him some instructions on how to set up his job files to use the same command line syntax with some small changes (`python <module>.py` instead of `luigi --module <module_name>`). Does that address your concerns? If not, let me know and we can talk further on what you're looking for.

**Comment by dylanjbarth** [comment]
hey @alexdebrie thanks for the quick response. 

I should have looked through the closed issues first -- you're right, the solution you described does work and in fact that is how we have been using luigi-monitor. 

I guess what I am looking for is an enhancement, not a bug -- in our production pipelines we have over 10 different entry points, each which need to have the snippet at the bottom to wrap the call in the luigi-monitor context manager. It would be awesome to not have to think about it and just trigger tasks from the command line with luigi-monitor. 

`luigi-monitor --module <module.dot.path> <Task>` 

The only question in my mind is where to store settings like the slack url. Perhaps we could use the luigi.cfg? 

What do you think in general? If you are into the idea I'm happy to put together a PR.

**Comment by alexdebrie** [comment]
@dylanjbarth That sounds great. It would make it a lot easier for people with existing luigi jobs to use luigi-monitor. I'd definitely appreciate the PR. For settings, I agree about using the Luigi config file.

**Comment by alexdebrie** [comment]
Fixed in #6
